In [ ]:
import ast
import pandas as pd
from jinja2 import Template

df = pd.read_csv("original/rollouts_original.csv")

problem_idx = [(p, idx) for idx, p in enumerate(list(df["Problem"].unique()))]

df["Problem Index"] = df["Problem"].apply(lambda x: [idx for p, idx in problem_idx if p == x][0])

accepted_df = df.loc[~(df["Judge Decisions"].str.contains("REJECT"))]
rejected_df = df.loc[df["Judge Decisions"].str.contains("REJECT")]

accepted_df["Conversation"] = accepted_df["Conversation"].apply(ast.literal_eval)
accepted_df["Judge Decisions"] = accepted_df["Judge Decisions"].apply(ast.literal_eval)
accepted_df["Conversation from student perspective"] = accepted_df["Conversation from student perspective"].apply(ast.literal_eval)
rejected_df["Judge Decisions"] = rejected_df["Judge Decisions"].apply(ast.literal_eval)
rejected_df["Conversation"] = rejected_df["Conversation"].apply(ast.literal_eval)
rejected_df["Conversation from student perspective"] = rejected_df["Conversation from student perspective"].apply(ast.literal_eval)

def student_to_teacher_perspective(problem, student_name, conversation):
    teacher_conversation = []
    if pd.isnull(student_name):
        student_name = None
    system_prompt = Template(
        open("../prompt_templates/teacher_prompt.txt").read()
    ).render(problem=problem, student_name=student_name)
    teacher_conversation.append({"role": "system", "message": system_prompt})
    
    for i, msg in enumerate(conversation):
        if msg['role'] == "student":
            teacher_conversation.append({"role": "user", "message": msg['content']})
        else:
            teacher_conversation.append({"role": "assistant", "message": msg['content']})
    return teacher_conversation

accepted_df["Conversation from teacher perspective"] = accepted_df.apply(lambda row: student_to_teacher_perspective(row["Problem"], row["Student Name"], row["Conversation"]), axis=1)
rejected_df["Conversation from teacher perspective"] = rejected_df.apply(lambda row: student_to_teacher_perspective(row["Problem"], row["Student Name"], row["Conversation"]), axis=1)

/tmp/ipykernel_841523/3479729369.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accepted_df["Conversation"] = accepted_df["Conversation"].apply(ast.literal_eval)
/tmp/ipykernel_841523/3479729369.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accepted_df["Judge Decisions"] = accepted_df["Judge Decisions"].apply(ast.literal_eval)
/tmp/ipykernel_841523/3479729369.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accepted_df["Conversation from student perspective"] = accepted_df["Conversation from student perspective"].apply(ast.literal_eval)
/tmp/ipykernel_841523/3479729369.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rejected_df["Judge Decisions"] = rejected_df["Judge Decisions"].apply(ast.literal_eval)
/tmp/ipykernel_841523/3479729369.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rejected_df["Conversation"] = rejected_df["Conversation"].apply(ast.literal_eval)
/tmp/ipykernel_841523/3479729369.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rejected_df["Conversation from student perspective"] = rejected_df["Conversation from student perspective"].apply(ast.literal_eval)
/tmp/ipykernel_841523/3479729369.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accepted_df["Conversation from teacher perspective"] = accepted_df.apply(lambda row: student_to_teacher_perspective(row["Problem"], row["Student Name"], row["Conversation"]), axis=1)
/tmp/ipykernel_841523/3479729369.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rejected_df["Conversation from teacher perspective"] = rejected_df.apply(lambda row: student_to_teacher_perspective(row["Problem"], row["Student Name"], row["Conversation"]), axis=1)

In [45]:
accepted_df.head()

,State,Problem,Answer,Conversation,Type,Student Persona,Student Name,Judge Decisions,Solutions,Rewards,Initial Attempts,Initial Rewards,Conversation from student perspective,Problem Index,Conversation from teacher perspective
3,END,Joe bikes $x$ miles East at $20$ mph to hi...,10.0,"[{'role': 'teacher', 'content': 'Sure! Let's s...",GUIDED,simple_student,Alex,{'does_not_leak_answer': [{'reasoning': 'The t...,"[""**Problem:**\n\nJoe bikes $x$ miles East at ...","[0.0, 0.0, 0.0, 0.0]",[],[],"[{'role': 'user', 'content': 'Sure! Let's star...",0,"[{'role': 'system', 'message': ' You are taske..."
9,END,If $(2x+4)^{2010} = a_0 + a_1x + a_2x^2 + \ldo...,0.0,"[{'role': 'student', 'content': 'Here is my at...",ATTEMPTED,simple_student,Riley,{'does_not_leak_answer': [{'reasoning': 'The t...,"[""**Problem:**\nFind the remainder when $a_0 +...","[0.0, 0.0, 0.0, 0.0]",[],[],"[{'role': 'assistant', 'content': 'Here is my ...",1,"[{'role': 'system', 'message': ' You are taske..."
11,END,If $(2x+4)^{2010} = a_0 + a_1x + a_2x^2 + \ldo...,0.0,"[{'role': 'student', 'content': 'Here is my at...",ATTEMPTED,simple_student,Riley,{'does_not_leak_answer': [{'reasoning': 'The t...,['**Problem 1: \\((3x + 2)^{10}\\)**\n\nTo fin...,"[0.0, 0.0, 0.0, 0.0]",[],[],"[{'role': 'assistant', 'content': 'Here is my ...",1,"[{'role': 'system', 'message': ' You are taske..."
12,END,If $(2x+4)^{2010} = a_0 + a_1x + a_2x^2 + \ldo...,0.0,"[{'role': 'student', 'content': 'Here is my at...",ATTEMPTED,simple_student,Riley,{'does_not_leak_answer': [{'reasoning': 'The t...,['**Complete Solution**\n\n**Problem 4**\n\nGi...,"[0.0, 0.0, 0.0, 0.0]",[],[],"[{'role': 'assistant', 'content': 'Here is my ...",1,"[{'role': 'system', 'message': ' You are taske..."
14,END,If $(2x+4)^{2010} = a_0 + a_1x + a_2x^2 + \ldo...,0.0,"[{'role': 'student', 'content': 'Here is my at...",ATTEMPTED,simple_student,Riley,{'does_not_leak_answer': [{'reasoning': 'The t...,"[""**Problem:**\nGiven the polynomial \\(P(x) =...","[1.0, 1.0, 1.0, 1.0]",[],[],"[{'role': 'assistant', 'content': 'Here is my ...",1,"[{'role': 'system', 'message': ' You are taske..."

In [46]:
rejected_df.head()

,State,Problem,Answer,Conversation,Type,Student Persona,Student Name,Judge Decisions,Solutions,Rewards,Initial Attempts,Initial Rewards,Conversation from student perspective,Problem Index,Conversation from teacher perspective
0,END,Joe bikes $x$ miles East at $20$ mph to hi...,10.0,"[{'role': 'teacher', 'content': 'Sure! Let's b...",GUIDED,simple_student,Alex,{'does_not_leak_answer': [{'reasoning': 'The t...,[],[],[],[],"[{'role': 'user', 'content': 'Sure! Let's brea...",0,"[{'role': 'system', 'message': ' You are taske..."
1,END,Joe bikes $x$ miles East at $20$ mph to hi...,10.0,"[{'role': 'teacher', 'content': 'Sure, let's b...",GUIDED,simple_student,Alex,{'does_not_leak_answer': [{'reasoning': 'The t...,[],[],[],[],"[{'role': 'user', 'content': 'Sure, let's brea...",0,"[{'role': 'system', 'message': ' You are taske..."
2,END,Joe bikes $x$ miles East at $20$ mph to hi...,10.0,"[{'role': 'teacher', 'content': 'Let's start b...",GUIDED,simple_student,Alex,{'does_not_leak_answer': [{'reasoning': 'The t...,[],[],[],[],"[{'role': 'user', 'content': 'Let's start by b...",0,"[{'role': 'system', 'message': ' You are taske..."
4,END,Joe bikes $x$ miles East at $20$ mph to hi...,10.0,"[{'role': 'teacher', 'content': 'Sure! Let's b...",GUIDED,simple_student,Alex,{'does_not_leak_answer': [{'reasoning': 'The t...,[],[],[],[],"[{'role': 'user', 'content': 'Sure! Let's brea...",0,"[{'role': 'system', 'message': ' You are taske..."
5,END,Joe bikes $x$ miles East at $20$ mph to hi...,10.0,"[{'role': 'teacher', 'content': 'Sure, Alex! L...",GUIDED,simple_student,Alex,{'does_not_leak_answer': [{'reasoning': 'The t...,[],[],[],[],"[{'role': 'user', 'content': 'Sure, Alex! Let'...",0,"[{'role': 'system', 'message': ' You are taske..."

In [47]:
accepted_df.loc[accepted_df["Student Name"].isnull()]["Conversation from teacher perspective"].iloc[0]

[{'role': 'system',
  'message': '\nYou are tasked with being a teacher and helping a student with a math problem.\n\n\nYou must not reveal the answer to the problem to the student at any point in time.\nYour task is to guide the student to have a complete understanding of the problem.\nEven if the student is already able to solve the problem, you should help them understand and improve the solution so that they get as high of a grade as possible.\n\nIf possible, do not respond with overly long responses to the student.\n\n\n\nYou can end a conversation by writing <end_of_conversation>, please try to end conversations as soon as they are finished instead of prolonging them if not needed. But do not end them prematurely either.\n\nHere is the math problem:\nThis year in October, our school received a donation of footballs, basketballs, and volleyballs totaling 20 balls from a health and pharmaceutical company, with a total value of 330 yuan. The prices of these balls are 60 yuan for each football, 30 yuan for each basketball, and 10 yuan for each volleyball. Calculate the number of volleyballs. Express your answer as a positive integer.'},
 {'role': 'user',
  'message': "Here is my attempt at this problem: To solve this problem, let's denote the number of footballs as F, basketballs as B, and volleyballs as V. \n\nGiven that the total number of balls is 20, we can write the equation:\nF + B + V = 20\n\nWe also know the total value of the balls is 330 yuan, and their respective prices are 60 yuan, 30 yuan, and 10 yuan. So, the value equation can be written as:\n60F + 30B + 10V = 330\n\nNow, we have a system of two equations. However, we can simplify the process by using substitution or elimination method. \n\nTo simplify the problem, let's isolate one of the variables, such as B, in the first equation:\nB = 20 - F - V\n\nSubstituting this expression into the value equation, we get:\n60F + 30(20 - F - V) + 10V = 330\n\nSimplifying this expression, we get:\n60F + 600 - 30F - 30V + 10V = 330\n\nCombine like terms:\n30F + 600 - 20V = 330\n\nNow, let's simplify and isolate V:\n30F - 20V = -270\n20V = 30F + 270\nV = (30F + 270) / 20\n\nHowever, this is not the most efficient way to solve this problem. We can use the fact that each football costs 60 yuan, each basketball costs 30 yuan, and each volleyball costs 10 yuan. \n\nSince the total value of the balls is 330 yuan, let's try to find the number of volleyballs directly. \n\nLet's denote the number of volleyballs as V. We know that the total value of the volleyballs is 10V yuan. \n\nThe total value of the footballs is 60F yuan, and the total value of the basketballs is 30B yuan. \n\nSince F + B + V = 20, we can rewrite B as 20 - F - V.\n\nThe total value of the balls is:\n60F + 30B + 10V = 60F + 30(20 - F - V) + 10V\n= 60F + 600 - 30F - 30V + 10V\n= 30F + 600 - 20V\n= 330\n\nCombine like terms:\n30F - 20V = -270\n20V = 30F + 270\nV = (30F + 270) / 20\n\nHowever, this is not the most efficient way to solve this problem. Since the total value of the volleyballs is 10V yuan, let's try to find V directly.\n\nWe know that the total value of the balls is 330 yuan. Each football is 60 yuan, each basketball is 30 yuan, and each volleyball is 10 yuan.\n\nLet's assume the number of volleyballs is V. The total value of the volleyballs is 10V. The remaining amount of the total value is 330 - 10V.\n\nThe remaining balls are (20 - V), and their total value is 60F + 30B.\n\nSince there are (20 - V) balls left, we can assume that the number of footballs and basketballs is (20 - V).\n\nThe total value of the remaining balls is:\n60F + 30B = 330 - 10V\n\nHowever, this is not the most efficient way to solve this problem. Since we know the prices of the balls and the total value of the balls, we can find the number of volleyballs directly.\n\nLet's assume the number of volleyballs is V. The total value of the volleyballs is 10V.\n\nThe remaining amount of the total value is 330 - 10V.\n\nWe know that the total number of balls is 20. If we assume that the number of volleyballs is V, then the number of footballs and basketballs is (20 - V).\n\nSince each football is 60 yuan and each basketball is 30 yuan, the total value of the remaining balls is:\n60F + 30B = (60 + 30)(20 - V)\n= 90(20 - V)\n\nSince the total value of the balls is 330 yuan, we can set up the equation:\n90(20 - V) + 10V = 330\n\nSimplifying this expression, we get:\n1800 - 90V + 10V = 330\n\nCombine like terms:\n1800 - 80V = 330\n\nNow, let's isolate V:\n80V = 1800 - 330\n80V = 1470\nV = 1470 / 80\nV = 18.375\n\nHowever, this is not the most efficient way to solve this problem. Since we know the prices of"},
 {'role': 'assistant',
  'message': "Let's simplify the problem more efficiently. We already have two key equations:\n\n1. \\( F + B + V = 20 \\) (total number of balls)\n2. \\( 60F + 30B + 10V = 330 \\) (total value of the balls)\n\nWe want to find the number of volleyballs, \\( V \\).\n\nLet's use a simpler approach: \n\n1. **Assume the number of volleyballs and substitute**: Let's assume \\( V = x \\), and then we can express the number of footballs and basketballs in terms of \\( x \\).\n\n2. **Simplify the value equation**: Notice that volleyballs are the cheapest, so if we increase the number of volleyballs, we reduce the overall cost. This can help us find \\( V \\) directly.\n\nLet's try to find how many volleyballs could make the total value 330 yuan:\n\n- If there are no volleyballs (\\( V = 0 \\)), the total value is \\( 60F + 30B = 330 \\), which is not possible with integer solutions.\n- Let's try \\( V = 1 \\): Then the value equation becomes \\( 60F + 30B + 10 \\cdot 1 = 330 \\), or \\( 60F + 30B = 320 \\).\n\nIf we increase \\( V \\), the value of the volleyballs increases, and the sum of \\( 60F + 30B \\) decreases. We need to find a value of \\( V \\) that keeps the total sum as 330.\n\nTry \\( V = 10 \\):\n\n- If \\( V = 10 \\), then \\( 10 \\cdot 10 = 100 \\) is the value of the volleyballs. \n- The remaining value for footballs and basketballs is \\( 330 - 100 = 230 \\).\n\nNow, solve \\( 60F + 30B = 230 \\):\n- \\( F + B = 20 - 10 = 10 \\)\n\nWe solve these two equations:\n1. \\( F + B = 10 \\)\n2. \\( 60F + 30B = 230 \\)\n\nLet's solve these step by step."},
 {'role': 'user',
  'message': "Let's solve the two equations step by step:\n\nWe have:\n1. \\( F + B = 10 \\)\n2. \\( 60F + 30B = 230 \\)\n\nTo simplify the second equation, we can divide it by 30:\n\\( 2F + B = \\frac{230}{30} \\)\n\\( 2F + B = \\frac{23}{3} \\)\n\nSince F and B are integers, we can multiply both sides of the equation by 3 to eliminate the fraction:\n\\( 6F + 3B = 23 \\)\n\nNow we have two equations:\n1. \\( F + B = 10 \\)\n2. \\( 6F + 3B = 23 \\)\n\nLet's multiply the first equation by 3 to make it easier to solve:\n\\( 3F + 3B = 30 \\)\n\nNow we can subtract this equation from the second equation:\n\\( 6F + 3B - (3F + 3B) = 23 - 30 \\)\n\\( 3F = -7 \\)\n\nSince F cannot be negative, we made an incorrect assumption. Let's go back to the original equations:\n\nWe have:\n1. \\( F + B = 10 \\)\n2. \\( 60F + 30B = 230 \\)\n\nWe also know that the total number of balls is 20, so:\n\\( F + B + V = 20 \\)\n\nLet's substitute \\( V = 10 \\) into the equation:\n\\( F + B + 10 = 20 \\)\n\\( F + B = 10 \\)\n\nWe already know this equation. Let's think about how to find the number of volleyballs \\( V \\) using a different approach.\n\nSince each volleyball costs 10 yuan, the total value of the volleyballs is \\( 10V \\) yuan.\n\nThe remaining amount of the total value is \\( 330 - 10V \\).\n\nWe know that the total number of balls is 20. If we assume that the number of volleyballs is \\( V \\), then the number of footballs and basketballs is \\( 20 - V \\).\n\nSince each football is 60 yuan and each basketball is 30 yuan, the total value of the remaining balls is:\n\\( 60F + 30B = (60 + 30)(20 - V) \\)\n\nHowever, this is not the most efficient way to solve this problem. Let's go back to the original equations and try a different approach.\n\nWe have:\n1. \\( F + B + V = 20 \\)\n2. \\( 60F + 30B + 10V = 330 \\)\n\nLet's try to find the number of volleyballs \\( V \\) by using the fact that the total value of the balls is 330 yuan.\n\nSince the total value of the volleyballs is \\( 10V \\) yuan, the remaining amount of the total value is \\( 330 - 10V \\).\n\nThe remaining amount of the total value is the total value of the footballs and basketballs:\n\\( 60F + 30B = 330 - 10V \\)\n\nWe also know that the total number of balls is 20. If we assume that the number of volleyballs is \\( V \\), then the number of footballs and basketballs is \\( 20 - V \\).\n\nLet's substitute \\( 20 - V \\) for \\( F + B \\) in the second equation:\n\\( 60(20 - V) + 30B = 330 - 10V \\)\n\nSimplifying this expression, we get:\n\\( 1200 - 60V + 30B = 330 - 10V \\)\n\nCombine like terms:\n\\( 1200 - 50V + 30B = 330 \\)\n\nNow, let's isolate V:\n\\( 50V = 1200 - 330 + 30B \\)\n\\( 50V = 870 + 30B \\)\n\\( V = \\frac{870 + 30B}{50} \\)\n\nHowever, this is not the most efficient way to solve this problem."},
 {'role': 'assistant',
  'message': "Let's simplify the approach even further. We already have two key equations:\n\n1. \\( F + B + V = 20 \\)\n2. \\( 60F + 30B + 10V = 330 \\)\n\nWe can start by simplifying the second equation. Notice that the value equation can be simplified by dividing everything by 10:\n\n1. \\( F + B + V = 20 \\)\n2. \\( 6F + 3B + V = 33 \\)\n\nNow, let's isolate one of the variables. We can try to eliminate \\( V \\) by subtracting the first equation from the second:\n\n\\[ (6F + 3B + V) - (F + B + V) = 33 - 20 \\]\n\nThis simplifies to:\n\n\\[ 5F + 2B = 13 \\]\n\nNow we have a simpler equation to work with:\n\n\\[ 5F + 2B = 13 \\]\n\nWe need to find integer solutions for \\( F \\) and \\( B \\). Let's test some values for \\( F \\):\n\nIf \\( F = 1 \\):\n\\[ 5(1) + 2B = 13 \\]\n\\[ 5 + 2B = 13 \\]\n\\[ 2B = 8 \\]\n\\[ B = 4 \\]\n\nSo, \\( F = 1 \\) and \\( B = 4 \\).\n\nLet's check if these values satisfy the original first equation:\n\\[ F + B + V = 20 \\]\n\\[ 1 + 4 + V = 20 \\]\n\\[ V = 15 \\]\n\nNow, let's verify the total value:\n\\[ 60F + 30B + 10V = 330 \\]\n\\[ 60(1) + 30(4) + 10(15) = 330 \\]\n\\[ 60 + 120 + 150 = 330 \\]\n\nThe values satisfy the equation, so the number of volleyballs \\( V \\) is \\(\\boxed{15}\\)."},
 {'role': 'user',
  'message': "Yes, that's correct. We found that the number of volleyballs \\( V \\) is 15. \n\nTo verify the result, let's check if the values of \\( F \\), \\( B \\), and \\( V \\) satisfy the original equations:\n\n1. \\( F + B + V = 20 \\)\n\\( 1 + 4 + 15 = 20 \\)\n\nThe equation is satisfied.\n\n2. \\( 60F + 30B + 10V = 330 \\)\n\\( 60(1) + 30(4) + 10(15) = 330 \\)\n\\( 60 + 120 + 150 = 330 \\)\n\nThe equation is also satisfied.\n\nTherefore, the number of volleyballs \\( V \\) is indeed 15. \n\nI'm glad we were able to simplify the problem and find the correct solution together. Thank you for your guidance and patience. \n\nNow, let's review the steps we took to solve the problem:\n\n1. We simplified the value equation by dividing everything by 10.\n2. We eliminated \\( V \\) by subtracting the first equation from the second.\n3. We found a simpler equation \\( 5F + 2B = 13 \\) to work with.\n4. We tested some values for \\( F \\) and found that \\( F = 1 \\) and \\( B = 4 \\) satisfied the equation.\n5. We checked if these values satisfied the original equations and found that the number of volleyballs \\( V \\) is indeed 15.\n\nI hope this review helps. Let me know if you have any further questions or if there's anything else I can help you with."},
 {'role': 'assistant',
  'message': "Great job! You've reviewed the solution step-by-step and verified the results. Here’s a concise summary of the key steps to ensure you understand the process thoroughly:\n\n1. **Simplify the Value Equation:**\n   We started with the value equation:\n   \\[\n   60F + 30B + 10V = 330\n   \\]\n   Dividing everything by 10, we get:\n   \\[\n   6F + 3B + V = 33\n   \\]\n\n2. **Eliminate One Variable:**\n   We subtracted the first key equation \\( F + B + V = 20 \\) from the simplified value equation:\n   \\[\n   (6F + 3B + V) - (F + B + V) = 33 - 20\n   \\]\n   This simplifies to:\n   \\[\n   5F + 2B = 13\n   \\]\n\n3. **Solve for Integer Solutions:**\n   We tested integer values for \\( F \\) and found:\n   - For \\( F = 1 \\):\n     \\[\n     5(1) + 2B = 13\n     \\]\n     \\[\n     5 + 2B = 13\n     \\]\n     \\[\n     2B = 8\n     \\]\n     \\[\n     B = 4\n     \\]\n\n4. **Find \\( V \\):**\n   Using \\( F = 1 \\) and \\( B = 4 \\) in the first key equation:\n   \\[\n   F + B + V = 20\n   \\]\n   \\[\n   1 + 4 + V = 20\n   \\]\n   \\[\n   V = 15\n   \\]\n\n5. **Verification:**\n   We checked both original equations:\n   - \\( 1 + 4 + 15 = 20 \\) (First equation satisfied)\n   - \\( 60(1) + 30(4) + 10(15) = 330 \\) (Second equation satisfied)\n\nBy going through these steps, you’ve correctly identified that the number of volleyballs \\( V \\) is 15.\n\nIf you have any more questions or need further assistance, feel free to ask!"},
 {'role': 'user',
  'message': "I'm glad I was able to break down the problem into manageable steps and find the correct solution. Your concise summary of the key steps is very helpful in understanding the process.\n\nTo confirm, I'll reiterate the solution steps:\n\n1. Simplify the value equation by dividing everything by 10.\n2. Eliminate one variable by subtracting the first key equation from the simplified value equation.\n3. Solve for integer solutions by testing values for F.\n4. Find V using the values of F and B in the first key equation.\n5. Verify the results by checking both original equations.\n\nI'll make sure to remember these steps for future problems. Thank you again for your guidance and patience. If I have any more questions or need further assistance, I'll be sure to ask."},
 {'role': 'assistant',
  'message': "That's a great summary! You've done an excellent job breaking down the problem into clear, manageable steps. Here’s your summary again for clarity:\n\n1. **Simplify the Value Equation:**\n   \\[\n   60F + 30B + 10V = 330 \\quad \\text{becomes} \\quad 6F + 3B + V = 33\n   \\]\n\n2. **Eliminate One Variable:**\n   Subtract the first key equation \\( F + B + V = 20 \\) from the simplified value equation:\n   \\[\n   (6F + 3B + V) - (F + B + V) = 33 - 20 \\quad \\text{becomes} \\quad 5F + 2B = 13\n   \\]\n\n3. **Solve for Integer Solutions:**\n   Test integer values for \\( F \\):\n   - For \\( F = 1 \\):\n     \\[\n     5(1) + 2B = 13 \\quad \\text{becomes} \\quad 5 + 2B = 13 \\quad \\text{giving} \\quad 2B = 8 \\quad \\text{so} \\quad B = 4\n     \\]\n\n4. **Find \\( V \\):**\n   Use \\( F = 1 \\) and \\( B = 4 \\) in the first key equation:\n   \\[\n   F + B + V = 20 \\quad \\text{becomes} \\quad 1 + 4 + V = 20 \\quad \\text{so} \\quad V = 15\n   \\]\n\n5. **Verification:**\n   Check both original equations:\n   - \\( 1 + 4 + 15 = 20 \\) (First equation satisfied)\n   - \\( 60(1) + 30(4) + 10(15) = 330 \\) (Second equation satisfied)\n\nYou’ve got it! This method will definitely help you solve similar problems efficiently. If you have any more questions or need further assistance in the future, don’t hesitate to ask. Keep up the great work!\n\n<end_of_conversation>"}]

In [56]:
accepted_df["Conversation from teacher perspective"].iloc[0]

[{'role': 'system',
  'message': '\nYou are tasked with being a teacher and helping a student named Alex with a math problem.\n\n\nYou must not reveal the answer to the problem to the student at any point in time.\nYour task is to guide the student to have a complete understanding of the problem.\nEven if the student is already able to solve the problem, you should help them understand and improve the solution so that they get as high of a grade as possible.\n\nIf possible, do not respond with overly long responses to the student.\n\n\n\nYou can end a conversation by writing <end_of_conversation>, please try to end conversations as soon as they are finished instead of prolonging them if not needed. But do not end them prematurely either.\n\nHere is the math problem:\nJoe bikes  $x$  miles East at  $20$  mph to his friend’s house. He then turns South and bikes  $x$  miles at  $20$  mph to the store. Then, Joe turns East again and goes to his grandma’s house at  $14$  mph. On this last leg, he has to carry ﬂour he bought for her at the store. Her house is  $2$  more miles from the store than Joe’s friend’s house is from the store. Joe spends a total of 1 hour on the bike to get to his grandma’s house. If Joe then rides straight home in his grandma’s helicopter at  $78$  mph, how many minutes does it take Joe to get home from his grandma’s house'},
 {'role': 'assistant',
  'message': "Sure! Let's start by breaking down Joe's journey into segments and understanding each part step by step.\n\n1. **First Segment: East to his friend’s house**\n   - Distance: \\( x \\) miles\n   - Speed: 20 mph\n   - Time: \\( \\frac{x}{20} \\) hours\n\n2. **Second Segment: South to the store**\n   - Distance: \\( x \\) miles\n   - Speed: 20 mph\n   - Time: \\( \\frac{x}{20} \\) hours\n\n3. **Third Segment: East to his grandma’s house**\n   - Distance: \\( x + 2 \\) miles (since Grandma’s house is 2 miles further East than the store)\n   - Speed: 14 mph\n   - Time: \\( \\frac{x + 2}{14} \\) hours\n\n4. **Total time for the bike ride:**\n   - Total time = Time for first segment + Time for second segment + Time for third segment\n   - Total time = \\( \\frac{x}{20} + \\frac{x}{20} + \\frac{x + 2}{14} \\)\n   - Total time = \\( \\frac{x}{10} + \\frac{x + 2}{14} \\)\n\nWe know that the total time is 1 hour, so we set up the equation:\n\\[ \\frac{x}{10} + \\frac{x + 2}{14} = 1 \\]\n\nNow, let's solve this equation to find \\( x \\).\n<continue>"},
 {'role': 'user',
  'message': "So to start solving the equation, I should first get a common denominator for the fractions, right? That would be 70. \n\nSo, I'd multiply the first fraction by 7 and the second fraction by 5. This will give me:\n\n\\[ \\frac{7x}{70} + \\frac{5x + 10}{70} = 1 \\]\n\nThen, I can combine the fractions to get:\n\n\\[ \\frac{7x + 5x + 10}{70} = 1 \\]\n\nNow, I'm not sure what to do next. Can you help me out?"},
 {'role': 'assistant',
  'message': "Absolutely! You're on the right track. Let's continue from where you left off:\n\nYou have:\n\n\\[ \\frac{7x + 5x + 10}{70} = 1 \\]\n\nCombine the like terms in the numerator:\n\n\\[ \\frac{12x + 10}{70} = 1 \\]\n\nTo eliminate the fraction, multiply both sides of the equation by 70:\n\n\\[ 12x + 10 = 70 \\]\n\nNext, subtract 10 from both sides to isolate the term with \\( x \\):\n\n\\[ 12x = 60 \\]\n\nNow, divide both sides by 12 to solve for \\( x \\):\n\n\\[ x = \\frac{60}{12} \\]\n\n\\[ x = 5 \\]\n\nSo, \\( x = 5 \\) miles.\n\nNow that we know \\( x \\), let's move on to the next part of the problem. Joe needs to ride straight home in his grandmother's helicopter at 78 mph. We need to find out how long it takes for Joe to get home from his grandmother's house.\n\nFirst, we need to calculate the straight-line distance from grandma’s house back to Joe’s starting point.\n\nJoe's journey can be visualized as forming a right-angled triangle. The legs of this triangle are:\n- Vertical leg: 5 miles (the southward journey to the store)\n- Horizontal leg: 5 + 2 = 7 miles (since Grandma’s house is 2 miles further east than the store)\n\nUsing the Pythagorean theorem:\n\n\\[ \\text{Straight-line distance} = \\sqrt{(5^2 + 7^2)} \\]\n\n\\[ \\text{Straight-line distance} = \\sqrt{25 + 49} \\]\n\n\\[ \\text{Straight-line distance} = \\sqrt{74} \\]\n\nNow, we need to find the time it takes for Joe to travel this distance at 78 mph.\n\n\\[ \\text{Time} = \\frac{\\text{Distance}}{\\text{Speed}} = \\frac{\\sqrt{74}}{78} \\]\n\nTo find the time in minutes, we multiply by 60 (since there are 60 minutes in an hour):\n\n\\[ \\text{Time in minutes} = \\left(\\frac{\\sqrt{74}}{78}\\right) \\times 60 \\]\n\nLet's simplify this:\n\n\\[ \\text{Time in minutes} = \\frac{60 \\sqrt{74}}{78} \\]\n\n\\[ \\text{Time in minutes} = \\frac{30 \\sqrt{74}}{39} \\]\n\nThis is the exact time in minutes. If you need a numerical approximation, you can use a calculator to find:\n\n\\[ \\text{Time in minutes} \\approx \\frac{30 \\times 8.602}{39} \\approx \\frac{258.06}{39} \\approx 6.6 \\]\n\nSo, it takes Joe approximately 6.6 minutes to get home from his grandma's house.\n\nIs this clear to you, or do you need any further explanation?"},
 {'role': 'user',
  'message': "I think I understand how you solved the problem. But, I'm a bit confused about why we needed to find the straight-line distance using the Pythagorean theorem. We already know the distance from Grandma's house to the store is 7 miles, and we know the vertical distance is 5 miles. Since Joe is riding straight back home in the helicopter, isn't the straight-line distance just the hypotenuse of the right triangle formed by the vertical and horizontal legs of Joe's journey?\n\nAnd, if that's the case, we could just use the Pythagorean theorem to find the hypotenuse, and then use that as the distance in our time calculation. Is that correct?"},
 {'role': 'assistant',
  'message': "You're absolutely right! I apologize for the unnecessary complexity in my previous explanation. Let's streamline it:\n\nGiven the right triangle formed by Joe's journey:\n\n- The vertical leg (southward journey to the store) is 5 miles.\n- The horizontal leg (journey from the store to grandma's house) is 7 miles.\n\nUsing the Pythagorean theorem:\n\n\\[ \\text{Straight-line distance} = \\sqrt{5^2 + 7^2} = \\sqrt{25 + 49} = \\sqrt{74} \\]\n\nNow, we can find the time it takes to travel this distance at 78 mph:\n\n\\[ \\text{Time} = \\frac{\\text{Distance}}{\\text{Speed}} = \\frac{\\sqrt{74}}{78} \\]\n\nConvert this time into minutes:\n\n\\[ \\text{Time in minutes} = \\frac{\\sqrt{74}}{78} \\times 60 \\]\n\nUsing a calculator to find the numerical value:\n\n\\[ \\text{Time in minutes} \\approx \\frac{8.602}{78} \\times 60 \\approx 0.1102 \\times 60 \\approx 6.6 \\]\n\nSo, the time it takes Joe to get home from his grandma’s house is approximately **6.6 minutes**.\n\nThank you for pointing out the unnecessary complexity. This is a much simpler and clearer way to solve the problem!"},
 {'role': 'user',
  'message': "I'm glad we were able to simplify the solution. I think I understand the whole problem now. Let me try to summarize what we did:\n\n1. We broke down Joe's journey into segments and found the total time for the bike ride.\n2. We set up an equation to solve for the distance \\( x \\) and found that \\( x = 5 \\) miles.\n3. We found the straight-line distance from grandma's house to Joe's starting point using the Pythagorean theorem.\n4. We calculated the time it takes for Joe to get home from his grandma's house at 78 mph.\n\nI feel more confident now that I understand the problem. Do you think I'm ready to try some practice problems on my own?"},
 {'role': 'assistant',
  'message': "Absolutely! You've done a great job following the steps and understanding the problem. It's wonderful that you feel more confident now.\n\nFeel free to try some practice problems on your own. Here are a couple to get you started:\n\n1. **Problem 1:**\n   - Joe walks 4 miles North, then 3 miles East, and finally 7 miles South to reach his destination. If Joe walks at a constant speed of 4 mph, how long does it take him to get to his destination?\n   - From his destination, Joe needs to walk directly back home. If Joe walks at the same speed, how long does it take him to get back home?\n\n2. **Problem 2:**\n   - Alex runs 6 miles East and then 8 miles North. He then runs back to the starting point. If Alex runs at a constant speed of 5 mph, how long does it take him to run back to the starting point?\n\nTake your time with these problems, and if you need any help or want to discuss your solutions, feel free to ask! Good luck!"},
 {'role': 'user',
  'message': "I'll try to solve the problems on my own. Here's my attempt:\n\n**Problem 1:**\n\n1. First, I need to find the distance from Joe's starting point to his destination. Since Joe walks 4 miles North and then 7 miles South, he ends up walking 3 miles South of his starting point. However, he also walks 3 miles East, so the distance from his starting point to his destination is the hypotenuse of a right triangle with legs 3 and 3.\n2. Using the Pythagorean theorem, I can find the hypotenuse:\n\\[ \\text{Hypotenuse} = \\sqrt{3^2 + 3^2} = \\sqrt{9 + 9} = \\sqrt{18} \\]\n3. Since Joe walks at a constant speed of 4 mph, I can find the time it takes him to get to his destination:\n\\[ \\text{Time} = \\frac{\\text{Distance}}{\\text{Speed}} = \\frac{\\sqrt{18}}{4} \\]\n4. To find the time in minutes, I can multiply by 60:\n\\[ \\text{Time in minutes} = \\frac{\\sqrt{18}}{4} \\times 60 \\]\n5. Now, to find the time it takes Joe to get back home, I can use the distance from his destination to his starting point. Since the distance is the same as the distance from his starting point to his destination, the time it takes him to get back home is the same as the time it takes him to get to his destination.\n\n**Problem 2:**\n\n1. First, I need to find the distance from Alex's starting point to his destination. Since Alex runs 6 miles East and then 8 miles North, I can use the Pythagorean theorem to find the hypotenuse:\n\\[ \\text{Hypotenuse} = \\sqrt{6^2 + 8^2} = \\sqrt{36 + 64} = \\sqrt{100} = 10 \\]\n2. Since Alex runs at a constant speed of 5 mph, I can find the time it takes him to run back to the starting point:\n\\[ \\text{Time} = \\frac{\\text{Distance}}{\\text{Speed}} = \\frac{10}{5} = 2 \\]\n3. To find the time in minutes, I can multiply by 60:\n\\[ \\text{Time in minutes} = 2 \\times 60 = 120 \\]\n\nI think I've solved the problems, but I'd love to get your feedback and make sure I'm on the right track!"},
 {'role': 'assistant',
  'message': "Great job! Your approach is correct, and your solutions are on the right track. Let's go through your answers step-by-step to ensure they are accurate.\n\n### Problem 1:\n1. **Distance Calculation:**\n   - Joe walks 4 miles North, then 3 miles South, ending up 1 mile North of the starting point (since \\(4 - 3 = 1\\)).\n   - Joe then walks 3 miles East.\n   - The distance from Joe's destination to the starting point is the hypotenuse of a right triangle with legs 1 mile (North-South) and 3 miles (East-West).\n   - Using the Pythagorean theorem:\n     \\[ \\text{Hypotenuse} = \\sqrt{1^2 + 3^2} = \\sqrt{1 + 9} = \\sqrt{10} \\]\n\n2. **Time to Destination:**\n   - Joe walks at 4 mph.\n   - Time to destination:\n     \\[ \\text{Time} = \\frac{\\sqrt{10}}{4} \\text{ hours} \\]\n   - Convert to minutes:\n     \\[ \\text{Time in minutes} = \\left(\\frac{\\sqrt{10}}{4}\\right) \\times 60 \\approx 7.9 \\text{ minutes} \\]\n\n3. **Time to Get Back Home:**\n   - The time to get back home is the same as the time to get to the destination.\n   - \\[ \\text{Time in minutes} \\approx 7.9 \\text{ minutes} \\]\n\n### Problem 2:\n1. **Distance Calculation:**\n   - Alex runs 6 miles East and 8 miles North.\n   - The distance from Alex's starting point to his destination is the hypotenuse of a right triangle with legs 6 miles and 8 miles.\n   - Using the Pythagorean theorem:\n     \\[ \\text{Hypotenuse} = \\sqrt{6^2 + 8^2} = \\sqrt{36 + 64} = \\sqrt{100} = 10 \\]\n\n2. **Time to Get Back Home:**\n   - Alex runs at 5 mph.\n   - Time to get back home:\n     \\[ \\text{Time} = \\frac{10}{5} = 2 \\text{ hours} \\]\n   - Convert to minutes:\n     \\[ \\text{Time in minutes} = 2 \\times 60 = 120 \\text{ minutes} \\]\n\nYour solutions are correct, and you've understood the concept well. Great job!\n\nIf you have any more problems or need further practice, feel free to ask!\n\n<end_of_conversation>"}]

In [ ]:
preference_dict = {
    "accepted": accepted_df["Conversation from teacher perspective"].tolist(),
    "accepted_problem_idx": accepted_df["Problem Index"].tolist(),
    "rejected": rejected_df["Conversation from teacher perspective"].tolist(),
    "rejected_problem_idx": rejected_df["Problem Index"].tolist()
}

import json

with open("preference.json", "w") as f:
    json.dump(preference_dict, f)